### ISSUE TITLE
module aufs not found on rhel 6.5

### ISSUE THREAD

**Issue by mvillis** [opscode-cookbooks/delivery-truck#2]
The latest cut of delivery-truck errors when running on RHEL 6.5 (failure to grab the aufs module).
See build stack from Delivery below:

Any ideas?

```
Starting job on builder build-node-ent_cluster-2.
Command: delivery job verify lint --server server1 --user builder --ent ent --org adt --project ent-java --for master --patchset 6 --change-id db64f88e-32cf-4bf6-82a0-623e3dfcecee --change add-delivery-config 
Chef Delivery
Loading configuration from /var/opt/delivery/workspace
Starting job for ent-java verify lint
Creating workspace
Cloning repository, and merging add-delivery-config to master
Configuring the job
Running the job
Setting up the builder
Starting Chef Client, version 12.0.3
resolving cookbooks for run list: ["delivery-truck::default"]
Synchronizing Cookbooks:
  - delivery-truck
  - aufs
  - docker
  - sudo
  - apt
  - modules
  - device-mapper
  - git
  - golang
  - homebrew
  - iptables
  - lxc
  - runit
  - sysctl
  - yum-epel
  - build-essential
  - dmg
  - windows
  - dpkg_autostart
  - polipo
  - iptables-ng
  - packagecloud
  - ohai
  - yum
  - chef_handler
Compiling Cookbooks...
Recipe: delivery-truck::default
  * chef_gem[kitchen-docker] action installWARN: Unresolved specs during Gem::Specification.reset:
      nokogiri (>= 1.4.0, ~> 1.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

    - install version 2.0.0 of package kitchen-docker
  * chef_gem[chefspec] action install
    - install version 4.1.1 of package chefspec
  * chef_gem[chef-sugar] action upgrade
    - upgrade package chef-sugar from uninstalled to 3.1.0
  Converging 12 resources
Recipe: aufs::module
  * modules[aufs] action load
    * execute[load module aufs] action run
      
      ================================================================================
      Error executing action `run` on resource 'execute[load module aufs]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of modprobe aufs  ----
      STDOUT: 
      STDERR: FATAL: Module aufs not found.
      ---- End output of modprobe aufs  ----
      Ran modprobe aufs  returned 1
      
      Cookbook Trace:
      ---------------
      /var/opt/delivery/workspace/chfrd2.domain/ent/adt/ent-java/master/verify/lint/cache/cookbooks/lxc/libraries/monkey.rb:20:in `monkey_shell_out!'
      
      Resource Declaration:
      ---------------------
      # In /var/opt/delivery/workspace/chfrd2.domain/ent/adt/ent-java/master/verify/lint/cache/cookbooks/modules/providers/default.rb
      
       42:   execute "load module #{new_resource.module}" do
       43:     command "modprobe #{new_resource.module} #{serializeOptions}"
       44:     not_if { mod_loaded?(new_resource.module) }
       45:   end
       46: end
      
      Compiled Resource:
      ------------------
      # Declared in /var/opt/delivery/workspace/chfrd2.domain/ent/adt/ent-java/master/verify/lint/cache/cookbooks/modules/providers/default.rb:42:in `block in class_from_file'
      
      execute("load module aufs") do
        action "run"
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "modprobe aufs "
        backup 5
        returns 0
        declared_type :execute
        cookbook_name "aufs"
        not_if { #code block }
      end
      
    
    ================================================================================
    Error executing action `load` on resource 'modules[aufs]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    execute[load module aufs] (/var/opt/delivery/workspace/chfrd2.domain/ent/adt/ent-java/master/verify/lint/cache/cookbooks/modules/providers/default.rb line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of modprobe aufs  ----
    STDOUT: 
    STDERR: FATAL: Module aufs not found.
    ---- End output of modprobe aufs  ----
    Ran modprobe aufs  returned 1
    
    Cookbook Trace:
    ---------------
    /var/opt/delivery/workspace/chfrd2.domain/ent/adt/ent-java/master/verify/lint/cache/cookbooks/lxc/libraries/monkey.rb:20:in `monkey_shell_out!'
    
    Resource Declaration:
    ---------------------
    # In /var/opt/delivery/workspace/chfrd2.domain/ent/adt/ent-java/master/verify/lint/cache/cookbooks/aufs/recipes/module.rb
    
      1: modules 'aufs' do
      2:   action :load
      3: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/opt/delivery/workspace/chfrd2.domain/ent/adt/ent-java/master/verify/lint/cache/cookbooks/aufs/recipes/module.rb:1:in `from_file'
    
    modules("aufs") do
      action [:load]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :modules
      cookbook_name "aufs"
      recipe_name "module"
      module "aufs"
    end
    

Running handlers:
[2015-04-27T17:09:19+10:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-27T17:09:19+10:00] ERROR: Exception handlers complete
[2015-04-27T17:09:19+10:00] FATAL: Stacktrace dumped to /var/opt/delivery/workspace/chfrd2.domain/ent/adt/ent-java/master/verify/lint/cache/chef-stacktrace.out
Chef Client failed. 3 resources updated in 88.231037987 seconds
[2015-04-27T17:09:20+10:00] ERROR: modules[aufs] (aufs::module line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[load module aufs] (/var/opt/delivery/workspace/chfrd2.domain/ent/adt/ent-java/master/verify/lint/cache/cookbooks/modules/providers/default.rb line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of modprobe aufs  ----
STDOUT: 
STDERR: FATAL: Module aufs not found.
---- End output of modprobe aufs  ----
Ran modprobe aufs  returned 1
[2015-04-27T17:09:20+10:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef Client failed
STDOUT: 
STDERR: 
```

**Comment by jonsmorrow** [comment]
For anyone hitting this issue please point at 54f502b752fb0a26aa4180fe0a7a3a376b242768  in your berks file instead of master. You wont get the new shinny docker stuff but at least your builds wont break until we get a better solution.
```
source "https://supermarket.chef.io"

metadata

cookbook 'delivery-truck',
  git: 'https://github.com/opscode-cookbooks/delivery-truck.git',
  ref: '54f502b752fb0a26aa4180fe0a7a3a376b242768'
```

**Comment by afiune** [comment]
Closing this issue since we are not using docker at the moment..
